### ISSUE TITLE
Map and examples are wrong for MedicationRequestStatusReason-Extension-3to4

### ISSUE THREAD

**Issue by declankieran** [NHSDigital/fhir-transforms#43]
https://github.com/NHSDigital/fhir-transforms/blob/develop/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_000.json

and

https://github.com/NHSDigital/fhir-transforms/blob/develop/resources/careconnect-to-ukcore/medicationrequest/expected/MedicationRequestStatusReason-Extension-3to4_001.json

Includes a Extension-UKCore-CodingSCTDescId extension.  The descriptionId uses a valueId instead of a valueIdentifier.  The expected (links above) and the map 

https://github.com/NHSDigital/fhir-transforms/blob/develop/resources/careconnect-to-ukcore/medicationrequest/maps/MedicationRequestStatusReason-Extension-3to4.map

need updated.

cc: @artronics @urchy @RNatarajanNHS

**Comment by declankieran** [comment]
There is an additional complication to this, again around uri values, the one I have in the example for MedicationRequestStatusReason-Extension-3to4 is

https://fhir.nhs.uk/STU3/StructureDefinition/Extension-coding-sctdescid

This data from live test systems, the uri for it in AllergyInolerance is 

https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid

I'm going to handle both in the maps.

**Comment by declankieran** [comment]
Resolved in https://github.com/NHSDigital/fhir-transforms/pull/44

**Comment by artronics** [comment]
@declankieran-nhsd I can't find any example covering `https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid` url case. Is it going to be in this PR or do we need to create another one?

**Comment by declankieran** [comment]
Yes good point, both have https://fhir.nhs.uk/STU3/StructureDefinition/Extension-coding-sctdescid, examples for https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid would be good for completeness, the map has been should work for both, so the pipeline should pass when the new examples are added.
