### ISSUE TITLE
Missing examples for ChangeSummary extension

### ISSUE THREAD

**Issue by artronics** [NHSDigital/fhir-transforms#48]
We have a ticket on our board [AMB-1085](https://nhsd-jira.digital.nhs.uk/browse/AMB-1085) addressing ChagneSummary extension however, currently there are no examples for this extension. As far as I know, this extension is one of those that are deprecated but I'm not entirely sure.

We need example(s) capturing the requirements for this extension.

CC: @declankieran-nhsd

**Comment by declankieran** [comment]
Map added for ChangeSummary here.  Deprecated, so it carries nothing over.  https://github.com/NHSDigital/fhir-transforms/commit/a60eac0ea4e0ce62075378b36fac00eff7f0ce82
