### ISSUE TITLE
Tag main branch with version number

### ISSUE THREAD

**Issue by artronics** [NHSDigital/fhir-transforms#49]
Moving forward, Bebop will continue fhir-converter work based on `main` branch state. This means:
1. We need to add github hooks to tag main branch with version number.
2. Merge current `develop` branch back to `main`
APIM has a method of doing versioning for API Producers project. There is a [github action](https://github.com/NHSDigital/fhir-converter/blob/c69adc885736482379241f609a1ed399a5804e91/.github/workflows/continuous-integration.yml#L53) and [corresponding script](https://github.com/NHSDigital/fhir-converter/blob/c69adc885736482379241f609a1ed399a5804e91/scripts/calculate_version.py) to bump the version.

**Comment by declankieran** [comment]
@artronics Just looking at this now, did you want develop merged into main as it was yesterday, and then the PR https://github.com/NHSDigital/fhir-transforms/pull/50 you've just raised to be also merged into main and tagged as v0.1.0?  If this is the case then that would be everything in develop, plus whats in the new PR, plus I'll need to add a maps for the new examples to make the pipeline pass.  I think it was said that there was a few things you'd actually like left out of the tagged release in main...

**Comment by declankieran** [comment]
https://github.com/NHSDigital/fhir-transforms/tree/v.0.1.0
